import mongoose, { Schema, model } from 'mongoose'


const userSchema = new mongoose.Schema({

  user_name: { type: String, required: true, unique: true , maxLength: 50 },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },

  firstName : { type: String, default: "" , maxLength: 30 },
  lastName : { type: String, default: "" , maxLength: 30 },
  bio: { type: String, default: "" , maxLength: 500 },
  profile_picture_url: { type: String, default: "" },

  credits: { type: Number, default: 10 },
  plan: { type: String, enum: ['free', 'pro', 'business'], default: 'free' },
  is_first_time: { type: Boolean, default: true },

  ecommerce_wishlist: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Product"
    }
  ]

}, {timestamps: true});



//// counts the total number of images generated by the user
userSchema.virtual("totalImages", {
  ref: "GeneratedImage",
  localField: "_id",
  foreignField: "user",
  count: true
});
userSchema.set("toJSON", { virtuals: true });
userSchema.set("toObject", { virtuals: true });





const User = mongoose.model("User", userSchema);


export default User;