import mongoose from "mongoose";

const trafficSessionSchema = new mongoose.Schema(
  {
    // A unique ID generated by the frontend (e.g., via uuid) for the session
    sessionId: {
      type: String,
      required: true,
      unique: true,
      index: true
    },
    // Optional: Tie the session to a logged-in user if they are authenticated
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null
    },
    // Device and browser info
    userAgent: {
      type: String,
      default: "unknown"
    },
    // Acquisition source (e.g., 'organic', 'direct', 'social', 'referral', 'email')
    source: {
      type: String,
      required: true,
      default: "direct",
      index: true
    },
    // The first page they landed on
    landingPage: {
      type: String,
      required: true
    },
    // Duration in seconds (updated periodically by frontend heartbeat or on tab close)
    duration: {
      type: Number,
      default: 0 
    },
    // Did they leave without taking any action?
    bounced: {
      type: Boolean,
      default: true 
    }
  },
  { timestamps: true }
);

// Helpful index for dashboard time-series queries
trafficSessionSchema.index({ createdAt: -1 });

export default mongoose.model("TrafficSession", trafficSessionSchema);