export default {
  "+ Add Horizontal Giude":"+ إضافة دليل أفقي",
  "+ Add Vertical Giude":"+ إضافة دليل عمودي",
  "2D View": "عرض ثنائي الأبعاد",
  "3D First Person": "ثلاثي الأبعاد من منظور الشخص الأول",
  "3D View": "عرض ثلاثي الأبعاد",
  "All": "الكل",
  "altitude": "الارتفاع",
  "Altitude": "الارتفاع",
  "Annotation": "التعليق التوضيحي",
  "Areas":"المناطق",
  "Change Language": "تغيير اللغة",
  "Cancel": "إلغاء",
  "Catalog" : "الكتالوج",
  "Chain selected Elements to Group":"ربط العناصر المحددة بالمجموعة",
  "Circular":"دائري",
  "Clear": "مسح",
  "color":"اللون",
  "Configure layer": "تكوين الطبقة",
  "Configure project": "تكوين المشروع",
  "Confirm": "تأكيد",
  "Copy":"نسخ",
  "Custom furniture": "أثاث مخصص",
  "Decoration": "الديكور",
  "Delete group and all Elements":"حذف المجموعة وجميع العناصر",
  "Delete layer": "حذف الطبقة",
  "Delete": "حذف",
  "Dimension": "البعد",
  "Elements on layer {0}": "العناصر على الطبقة {0}",
  "Elements":"العناصر",
  "Finishes": "التشطيبات",
  "Floor Thickness":"سمك الأرضية",
  "Furniture": "الأثاث",
  "Get Screenshot" : "الحصول على لقطة شاشة",
  "Group [{0}]":"المجموعة [{0}]",
  "Group's Barycenter":"مركز ثقل المجموعة",
  "Group's Elements":"عناصر المجموعة",
  "Groups":"المجموعات",
  "Guides":"الأدلة",
  "height": "الارتفاع",
  "Help": "مساعدة",
  "Holes":"الفتحات",
  "Horizontal":"أفقي",
  "Items":"العناصر",
  "Last Selected":"آخر تحديد",
  "Layer config": "إعدادات الطبقة",
  "Layer":"الطبقة",
  "Layers": "الطبقات",
  "Length":"الطول",
  "Lines":"الخطوط",
  "Load Project": "تحميل المشروع",
  "Load project": "تحميل المشروع",
  "Mouse X Coordinate":"إحداثيات الماوس X",
  "Mouse Y Coordinate":"إحداثيات الماوس Y",
  "Name": "الاسم",
  "New Empty Group":"مجموعة فارغة جديدة",
  "New Group from selected":"مجموعة جديدة من المحدد",
  "New layer": "طبقة جديدة",
  "New project": "مشروع جديد",
  "opacity": "الشفافية",
  "Open catalog": "فتح الكتالوج",
  "order": "الترتيب",
  "Pan": "تحريك",
  "Parametric ceiling": "السقف البارامتري",
  "Paste":"لصق",
  "Project config": "إعدادات المشروع",
  "Properties": "الخصائص",
  "Properties: [{0}] {1}": "الخصائص: [{0}] {1}",
  "Prototype":"النموذج الأولي",
  "Reference line": "خط المرجع",
  "Reset": "إعادة تعيين",
  "Room Height":"ارتفاع الغرفة",
  "Rotation" : "الدوران",
  "Save project": "حفظ المشروع",
  "Save": "حفظ",
  "Scene Zoom Level":"مستوى تكبير المشهد",
  "Search Element":"البحث عن عنصر",
  "Snap to Grid":"محاذاة للشبكة",
  "Snap to Guide":"محاذاة للدليل",
  "Snap to Line":"محاذاة للخط",
  "Snap to Point":"محاذاة للنقطة",
  "Snap to Segment":"محاذاة للقطعة",
  "texture":"النسيج",
  "thickness":"السماكة",
  "Toggle Group Visibility":"تبديل رؤية المجموعة",
  "Un-chain all Group\'s Elements and remove Group":"فك ربط جميع عناصر المجموعة وإزالة المجموعة",
  "Un-chain Element from Group":"فك ربط العنصر من المجموعة",
  "Undo (CTRL-Z)": "تراجع (CTRL-Z)",
  "Redo (CTRL-Y)": "إعادة (CTRL-Y)",
  "Undo": "تراجع",
  "Redo": "إعادة",
  "Unselect": "إلغاء التحديد",
  "Vertical":"عمودي",
  "width": "العرض",
  "Would you want to start a new Project?": "هل تريد بدء مشروع جديد؟",
  "Zoom in": "تكبير",
  "Zoom out": "تصغير",
  "2D Floor Plan": "مخطط 2D",
  "Loading planner...": "جارٍ تحميل المخطط...",
  "Multiple elements selected": "تم تحديد عدة عناصر",
  "Layer Items": "عناصر الطبقة",
  "Floor Information": "معلومات الأرضية",
  "Selected Layer": "الطبقة المحددة",
  "Layer 1": "الطبقة 1",
  "View": "عرض",
  "Camera": "الكاميرا",
  "👁️ Auto-hide Walls": "👁️ إخفاء الجدران تلقائيًا",
  "Structure": "الهيكل",
  "🧱 Walls": "🧱 الجدران",
  "🚪 Doors": "🚪 الأبواب",
  "🪟 Windows": "🪟 النوافذ",
  "Objects": "العناصر",
  "🪑 Furniture": "🪑 الأثاث",
  "Helpers & Guides": "المساعدات والإرشادات",
  "📐 Floor Grid": "📐 شبكة الأرضية",
  "➕ Axis Helpers": "➕ مساعدات المحاور",
  "📍 Markers": "📍 العلامات",
  "📏 Guides": "📏 الأدلة",
  "⬜ Bounding Boxes": "⬜ مربعات الإحاطة",
  "X": "X",
  "Y": "Y",
  "Errors": "الأخطاء",
  "Warnings": "التحذيرات",
  "Millimetres (mm)": "مليمترات (mm)",
  "Centimetres (cm)": "سنتيمترات (cm)",
  "Metres (m)": "أمتار (m)",
  "Inches (in)": "بوصات (in)",
  "Feet (ft)": "أقدام (ft)",
  "User": "مستخدم",
  "Free": "مجاني",
  "Floor Plan": "مخطط الطابق",
  "Gallery": "المعرض",
  "Render": "الرندر",
  "Floor Plan Tools": "أدوات المخطط",
  "Draw Room": "رسم غرفة",
  "Draw Straight Wall": "رسم جدار مستقيم",
  "Draw Area": "رسم منطقة",
  "Draw Arc Wall": "رسم جدار مقوس",
  "Doors & Windows": "الأبواب والنوافذ",
  "Door Opening": "فتحة باب",
  "Window Opening": "فتحة نافذة",
  "Beam": "عارضة",
  "Column": "عمود",
  "Measure Tool": "أداة القياس",
  "Measure distances and areas": "قياس المسافات والمساحات",
  "Align Objects": "محاذاة العناصر",
  "Align multiple objects": "محاذاة عدة عناصر",
  "Distribute": "توزيع",
  "Distribute objects evenly": "توزيع العناصر بالتساوي",
  "Group Objects": "تجميع العناصر",
  "Group multiple objects": "تجميع عدة عناصر",
  "Duplicate": "تكرار",
  "Duplicate selected objects": "تكرار العناصر المحددة",
  "Mirror": "عكس",
  "Mirror objects horizontally": "عكس العناصر أفقيًا",
  "Rotate": "تدوير",
  "Rotate objects precisely": "تدوير العناصر بدقة",
  "Scale": "تحجيم",
  "Scale objects proportionally": "تحجيم العناصر بشكل متناسب",
  "Design Gallery": "معرض التصاميم",
  "by": "بواسطة",
  "votes": "أصوات",
  "Snap": "التقاط",
  "Point": "نقطة",
  "Line": "خط",
  "Segment": "مقطع",
  "Grid": "شبكة",
  "Guide": "دليل",
  "Reset zoom": "إعادة ضبط التكبير",
  "Add layer": "إضافة طبقة",
  "Hide": "إخفاء",
  "Show": "إظهار",
  "Rename": "إعادة تسمية",
  "360 Walkthrough": "جولة 360",
  "360 Explorer": "مستكشف 360",
  "Render Settings": "إعدادات الرندر",
  "1K Render": "رندر 1K",
  "2K Render": "رندر 2K",
  "4K Render": "رندر 4K",
  "remaining": "متبقي",
  "Camera Controls": "عناصر تحكم الكاميرا",
  "Camera Height": "ارتفاع الكاميرا",
  "Camera Vertical Rotation": "الدوران العمودي للكاميرا",
  "Camera properties": "خصائص الكاميرا",
  "Height": "الارتفاع",
  "Angle": "الزاوية",
  "Captured Images": "الصور الملتقطة",
  "No captures yet": "لا توجد لقطات بعد",
  "Capture": "التقاط",
  "Captured Image": "الصورة الملتقطة",
  "Selected Capture Preview": "معاينة اللقطة المحددة",
  "Close preview": "إغلاق المعاينة",
  "Captured image thumbnail": "صورة مصغرة للّقطة",
  "Capture Again": "التقاط مرة أخرى",
  "Captured": "تم الالتقاط",
  "Ready": "جاهز",
  "Processing": "قيد المعالجة",
  "Failed": "فشل",
  "Click to preview": "انقر للمعاينة",
  "Waiting for backend response": "بانتظار استجابة الخادم",
  "Processing failed": "فشلت المعالجة",
  "Ready to render": "جاهز للرندر",
  "Room Type": "نوع الغرفة",
  "Frame Summary": "ملخص الإطار",
  "Capture a frame to generate a room summary.": "التقط إطارًا لإنشاء ملخص للغرفة.",
  "No visible items were detected in this frame.": "لم يتم اكتشاف عناصر ظاهرة في هذا الإطار.",
  "Render ready.": "الرندر جاهز."
};
