export default {
  "+ Add Horizontal Giude":"+ Add Horizontal Giude",
  "+ Add Vertical Giude":"+ Add Vertical Giude",
  "2D View": "2D View",
  "3D First Person": "3D First Person",
  "3D View": "3D View",
  "All": "All",
  "altitude": "altitude",
  "Altitude": "Altitude",
  "Areas":"Areas",
  "Change Language": "Change Language",
  "Cancel": "Cancel",
  "Catalog" : "Catalog",
  "Chain selected Elements to Group":"Chain selected Elements to Group",
  "Circular":"Circular",
  "Clear": "Clear",
  "Clear Measurements": "Clear Measurements",
  "color":"color",
  "Configure layer": "Configure layer",
  "Configure project": "Configure project",
  "Confirm": "Confirm",
  "Copy":"Copy",
  "Decoration": "Decoration",
  "Delete group and all Elements":"Delete group and all Elements",
  "Delete layer": "Delete layer",
  "Delete": "Delete",
  "Dimension": "Dimension",
  "Annotation": "Annotation",
  "Elements on layer {0}": "Elements on layer {0}",
  "Elements":"Elements",
  "Finishes": "Finishes",
  "Floor Thickness":"Floor Thickness",
  "Furniture": "Furniture",
  "Get Screenshot" : "Get Screenshot",
  "Group [{0}]":"Group [{0}]",
  "Group's Barycenter":"Group's Barycenter",
  "Group's Elements":"Group's Elements",
  "Groups":"Groups",
  "Guides":"Guides",
  "height": "height",
  "Help": "Help",
  "Holes":"Holes",
  "Horizontal":"Horizontal",
  "Items":"Items",
  "Last Selected":"Last Selected",
  "Layer config": "Layer config",
  "Layer":"Layer",
  "Layers": "Layers",
  "Length":"Length",
  "Lines":"Lines",
  "Load Project": "Load Project",
  "Load project": "Load project",
  "Measure": "Measure",
  "Measurement Unit":"Measurement Unit",
  "Mouse X Coordinate":"Mouse X Coordinate",
  "Mouse Y Coordinate":"Mouse Y Coordinate",
  "Name": "Name",
  "New Empty Group":"New Empty Group",
  "New Group from selected":"New Group from selected",
  "New layer": "New layer",
  "New project": "New project",
  "opacity": "opacity",
  "Open catalog": "Open catalog",
  "order": "order",
  "Pan": "Pan",
  "Parametric ceiling": "Parametric ceiling",
  "Paste":"Paste",
  "Project config": "Project config",
  "Properties": "Properties",
  "Properties: [{0}] {1}": "Properties: [{0}] {1}",
  "Prototype":"Prototype",
  "Reference line": "Reference line",
  "Reset": "Reset",
  "Rotation" : "Rotation",
  "Room Height":"Room Height",
  "Save project": "Save project",
  "Save": "Save",
  "Scene Zoom Level":"Scene Zoom Level",
  "Search Element":"Search Element",
  "Side A Faces Inside":"Side A Faces Inside",
  "Snap to Grid":"Snap to Grid",
  "Snap to Guide":"Snap to Guide",
  "Snap to Line":"Snap to Line",
  "Snap to Point":"Snap to Point",
  "Snap to Segment":"Snap to Segment",
  "texture":"texture",
  "thickness":"thickness",
  "Toggle Group Visibility":"Toggle Group Visibility",
  "Toolkit":"Toolkit",
  "Un-chain all Group\'s Elements and remove Group":"Un-chain all Group\'s Elements and remove Group",
  "Un-chain Element from Group":"Un-chain Element from Group",
  "Undo (CTRL-Z)": "Undo (CTRL-Z)",
  "Redo (CTRL-Y)": "Redo (CTRL-Y)",
  "Undo": "Undo",
  "Redo": "Redo",
  "Unselect": "Unselect",
  "Vertical":"Vertical",
  "width": "width",
  "Would you want to start a new Project?": "Would you want to start a new Project?",
  "Zoom in": "Zoom in",
  "Zoom out": "Zoom out",
  "Custom furniture": "Custom furniture",
  "2D Floor Plan": "2D Floor Plan",
  "Loading planner...": "Loading planner...",
  "Multiple elements selected": "Multiple elements selected",
  "Layer Items": "Layer Items",
  "Floor Information": "Floor Information",
  "Selected Layer": "Selected Layer",
  "Layer 1": "Layer 1",
  "View": "View",
  "Camera": "Camera",
  "👁️ Auto-hide Walls": "👁️ Auto-hide Walls",
  "Structure": "Structure",
  "🧱 Walls": "🧱 Walls",
  "🚪 Doors": "🚪 Doors",
  "🪟 Windows": "🪟 Windows",
  "Objects": "Objects",
  "🪑 Furniture": "🪑 Furniture",
  "Helpers & Guides": "Helpers & Guides",
  "📐 Floor Grid": "📐 Floor Grid",
  "➕ Axis Helpers": "➕ Axis Helpers",
  "📍 Markers": "📍 Markers",
  "📏 Guides": "📏 Guides",
  "⬜ Bounding Boxes": "⬜ Bounding Boxes",
  "X": "X",
  "Y": "Y",
  "Errors": "Errors",
  "Warnings": "Warnings",
  "Millimetres (mm)": "Millimetres (mm)",
  "Centimetres (cm)": "Centimetres (cm)",
  "Metres (m)": "Metres (m)",
  "Inches (in)": "Inches (in)",
  "Feet (ft)": "Feet (ft)",
  "User": "User",
  "Free": "Free",
  "Floor Plan": "Floor Plan",
  "Gallery": "Gallery",
  "Render": "Render",
  "Floor Plan Tools": "Floor Plan Tools",
  "Draw Room": "Draw Room",
  "Draw Straight Wall": "Draw Straight Wall",
  "Draw Area": "Draw Area",
  "Draw Arc Wall": "Draw Arc Wall",
  "Doors & Windows": "Doors & Windows",
  "Door Opening": "Door Opening",
  "Window Opening": "Window Opening",
  "Beam": "Beam",
  "Column": "Column",
  "Measure Tool": "Measure Tool",
  "Measure distances and areas": "Measure distances and areas",
  "Align Objects": "Align Objects",
  "Align multiple objects": "Align multiple objects",
  "Distribute": "Distribute",
  "Distribute objects evenly": "Distribute objects evenly",
  "Group Objects": "Group Objects",
  "Group multiple objects": "Group multiple objects",
  "Duplicate": "Duplicate",
  "Duplicate selected objects": "Duplicate selected objects",
  "Mirror": "Mirror",
  "Mirror objects horizontally": "Mirror objects horizontally",
  "Rotate": "Rotate",
  "Rotate objects precisely": "Rotate objects precisely",
  "Scale": "Scale",
  "Scale objects proportionally": "Scale objects proportionally",
  "Design Gallery": "Design Gallery",
  "by": "by",
  "votes": "votes",
  "Snap": "Snap",
  "Point": "Point",
  "Line": "Line",
  "Segment": "Segment",
  "Grid": "Grid",
  "Guide": "Guide",
  "Reset zoom": "Reset zoom",
  "Add layer": "Add layer",
  "Hide": "Hide",
  "Show": "Show",
  "Rename": "Rename"
};
