export default {
  "+ Add Horizontal Giude":"+ Agregar Guía Horizontal",
  "+ Add Vertical Giude":"+ Agregar Guía Vertical",
  "2D View": "Vista 2D",
  "3D First Person": "3D Primera Persona",
  "3D View": "Vista 3D",
  "All": "Todo",
  "altitude": "altitud",
  "Altitude": "Altitud",
  "Annotation": "Anotación",
  "Areas":"Áreas",
  "Change Language": "Cambiar idioma",
  "Cancel": "Cancelar",
  "Catalog" : "Catálogo",
  "Chain selected Elements to Group":"Encadenar Elementos seleccionados al Grupo",
  "Circular":"Circular",
  "Clear": "Limpiar",
  "color":"color",
  "Configure layer": "Configurar capa",
  "Configure project": "Configurar proyecto",
  "Confirm": "Confirmar",
  "Copy":"Copiar",
  "Custom furniture": "Muebles personalizados",
  "Decoration": "Decoración",
  "Delete group and all Elements":"Eliminar grupo y todos los Elementos",
  "Delete layer": "Eliminar capa",
  "Delete": "Eliminar",
  "Dimension": "Dimensión",
  "Elements on layer {0}": "Elementos en capa {0}",
  "Elements":"Elementos",
  "Finishes": "Acabados",
  "Floor Thickness":"Espesor del suelo",
  "Furniture": "Muebles",
  "Get Screenshot" : "Obtener Captura de Pantalla",
  "Group [{0}]":"Grupo [{0}]",
  "Group's Barycenter":"Baricentro del Grupo",
  "Group's Elements":"Elementos del Grupo",
  "Groups":"Grupos",
  "Guides":"Guías",
  "height": "altura",
  "Help": "Ayuda",
  "Holes":"Agujeros",
  "Horizontal":"Horizontal",
  "Items":"Elementos",
  "Last Selected":"Último Seleccionado",
  "Layer config": "Configuración de capa",
  "Layer":"Capa",
  "Layers": "Capas",
  "Length":"Longitud",
  "Lines":"Líneas",
  "Load Project": "Cargar Proyecto",
  "Load project": "Cargar proyecto",
  "Mouse X Coordinate":"Coordenada X del Ratón",
  "Mouse Y Coordinate":"Coordenada Y del Ratón",
  "Name": "Nombre",
  "New Empty Group":"Nuevo Grupo Vacío",
  "New Group from selected":"Nuevo Grupo desde seleccionados",
  "New layer": "Nueva capa",
  "New project": "Nuevo proyecto",
  "opacity": "opacidad",
  "Open catalog": "Abrir catálogo",
  "order": "orden",
  "Pan": "Desplazar",
  "Parametric ceiling": "Techo paramétrico",
  "Paste":"Pegar",
  "Project config": "Configuración de proyecto",
  "Properties": "Propiedades",
  "Properties: [{0}] {1}": "Propiedades: [{0}] {1}",
  "Prototype":"Prototipo",
  "Reference line": "Línea de referencia",
  "Reset": "Restablecer",
  "Room Height":"Altura de la habitación",
  "Rotation" : "Rotación",
  "Save project": "Guardar proyecto",
  "Save": "Guardar",
  "Scene Zoom Level":"Nivel de Zoom de la Escena",
  "Search Element":"Buscar Elemento",
  "Snap to Grid":"Ajustar a Cuadrícula",
  "Snap to Guide":"Ajustar a Guía",
  "Snap to Line":"Ajustar a Línea",
  "Snap to Point":"Ajustar a Punto",
  "Snap to Segment":"Ajustar a Segmento",
  "texture":"textura",
  "thickness":"grosor",
  "Toggle Group Visibility":"Alternar Visibilidad del Grupo",
  "Un-chain all Group\'s Elements and remove Group":"Desencadenar todos los Elementos del Grupo y eliminar Grupo",
  "Un-chain Element from Group":"Desencadenar Elemento del Grupo",
  "Undo (CTRL-Z)": "Deshacer (CTRL-Z)",
  "Redo (CTRL-Y)": "Rehacer (CTRL-Y)",
  "Undo": "Deshacer",
  "Redo": "Rehacer",
  "Unselect": "Deseleccionar",
  "Vertical":"Vertical",
  "width": "ancho",
  "Would you want to start a new Project?": "¿Desea iniciar un nuevo Proyecto?",
  "Zoom in": "Acercar",
  "Zoom out": "Alejar",
  "2D Floor Plan": "Plano 2D",
  "Loading planner...": "Cargando planificador...",
  "Multiple elements selected": "Múltiples elementos seleccionados",
  "Layer Items": "Elementos de capa",
  "Floor Information": "Información del piso",
  "Selected Layer": "Capa seleccionada",
  "Layer 1": "Capa 1",
  "View": "Vista",
  "Camera": "Cámara",
  "👁️ Auto-hide Walls": "👁️ Ocultar paredes automáticamente",
  "Structure": "Estructura",
  "🧱 Walls": "🧱 Paredes",
  "🚪 Doors": "🚪 Puertas",
  "🪟 Windows": "🪟 Ventanas",
  "Objects": "Objetos",
  "🪑 Furniture": "🪑 Muebles",
  "Helpers & Guides": "Ayudas y guías",
  "📐 Floor Grid": "📐 Cuadrícula del piso",
  "➕ Axis Helpers": "➕ Ayudas de ejes",
  "📍 Markers": "📍 Marcadores",
  "📏 Guides": "📏 Guías",
  "⬜ Bounding Boxes": "⬜ Cajas delimitadoras",
  "X": "X",
  "Y": "Y",
  "Errors": "Errores",
  "Warnings": "Advertencias",
  "Millimetres (mm)": "Milímetros (mm)",
  "Centimetres (cm)": "Centímetros (cm)",
  "Metres (m)": "Metros (m)",
  "Inches (in)": "Pulgadas (in)",
  "Feet (ft)": "Pies (ft)",
  "User": "Usuario",
  "Free": "Gratis",
  "Floor Plan": "Plano",
  "Gallery": "Galería",
  "Render": "Render",
  "Floor Plan Tools": "Herramientas de plano",
  "Draw Room": "Dibujar habitación",
  "Draw Straight Wall": "Dibujar pared recta",
  "Draw Area": "Dibujar área",
  "Draw Arc Wall": "Dibujar pared curva",
  "Doors & Windows": "Puertas y ventanas",
  "Door Opening": "Abertura de puerta",
  "Window Opening": "Abertura de ventana",
  "Beam": "Viga",
  "Column": "Columna",
  "Measure Tool": "Herramienta de medición",
  "Measure distances and areas": "Medir distancias y áreas",
  "Align Objects": "Alinear objetos",
  "Align multiple objects": "Alinear múltiples objetos",
  "Distribute": "Distribuir",
  "Distribute objects evenly": "Distribuir objetos uniformemente",
  "Group Objects": "Agrupar objetos",
  "Group multiple objects": "Agrupar múltiples objetos",
  "Duplicate": "Duplicar",
  "Duplicate selected objects": "Duplicar objetos seleccionados",
  "Mirror": "Espejar",
  "Mirror objects horizontally": "Espejar objetos horizontalmente",
  "Rotate": "Rotar",
  "Rotate objects precisely": "Rotar objetos con precisión",
  "Scale": "Escalar",
  "Scale objects proportionally": "Escalar objetos proporcionalmente",
  "Design Gallery": "Galería de diseños",
  "by": "por",
  "votes": "votos",
  "Snap": "Ajuste",
  "Point": "Punto",
  "Line": "Línea",
  "Segment": "Segmento",
  "Grid": "Cuadrícula",
  "Guide": "Guía",
  "Reset zoom": "Restablecer zoom",
  "Add layer": "Agregar capa",
  "Hide": "Ocultar",
  "Show": "Mostrar",
  "Rename": "Renombrar"
};
