export default {
  "+ Add Horizontal Giude":"+ Ajouter un Guide Horizontal",
  "+ Add Vertical Giude":"+ Ajouter un Guide Vertical",
  "2D View": "Vue 2D",
  "3D First Person": "3D Première Personne",
  "3D View": "Vue 3D",
  "All": "Tout",
  "altitude": "altitude",
  "Altitude": "Altitude",
  "Annotation": "Annotation",
  "Areas":"Zones",
  "Change Language": "Changer de langue",
  "Cancel": "Annuler",
  "Catalog" : "Catalogue",
  "Chain selected Elements to Group":"Chaîner les Éléments sélectionnés au Groupe",
  "Circular":"Circulaire",
  "Clear": "Effacer",
  "color":"couleur",
  "Configure layer": "Configurer le calque",
  "Configure project": "Configurer le projet",
  "Confirm": "Confirmer",
  "Copy":"Copier",
  "Custom furniture": "Meubles personnalisés",
  "Decoration": "Décoration",
  "Delete group and all Elements":"Supprimer le groupe et tous les Éléments",
  "Delete layer": "Supprimer le calque",
  "Delete": "Supprimer",
  "Dimension": "Dimension",
  "Elements on layer {0}": "Éléments sur le calque {0}",
  "Elements":"Éléments",
  "Finishes": "Finitions",
  "Floor Thickness":"Épaisseur du sol",
  "Furniture": "Mobilier",
  "Get Screenshot" : "Obtenir une Capture d'écran",
  "Group [{0}]":"Groupe [{0}]",
  "Group's Barycenter":"Barycentre du Groupe",
  "Group's Elements":"Éléments du Groupe",
  "Groups":"Groupes",
  "Guides":"Guides",
  "height": "hauteur",
  "Help": "Aide",
  "Holes":"Trous",
  "Horizontal":"Horizontal",
  "Items":"Éléments",
  "Last Selected":"Dernier Sélectionné",
  "Layer config": "Configuration du calque",
  "Layer":"Calque",
  "Layers": "Calques",
  "Length":"Longueur",
  "Lines":"Lignes",
  "Load Project": "Charger le Projet",
  "Load project": "Charger le projet",
  "Mouse X Coordinate":"Coordonnée X de la Souris",
  "Mouse Y Coordinate":"Coordonnée Y de la Souris",
  "Name": "Nom",
  "New Empty Group":"Nouveau Groupe Vide",
  "New Group from selected":"Nouveau Groupe à partir de la sélection",
  "New layer": "Nouveau calque",
  "New project": "Nouveau projet",
  "opacity": "opacité",
  "Open catalog": "Ouvrir le catalogue",
  "order": "ordre",
  "Pan": "Déplacer",
  "Parametric ceiling": "Plafond paramétrique",
  "Paste":"Coller",
  "Project config": "Configuration du projet",
  "Properties": "Propriétés",
  "Properties: [{0}] {1}": "Propriétés: [{0}] {1}",
  "Prototype":"Prototype",
  "Reference line": "Ligne de référence",
  "Reset": "Réinitialiser",
  "Room Height":"Hauteur de la pièce",
  "Rotation" : "Rotation",
  "Save project": "Enregistrer le projet",
  "Save": "Enregistrer",
  "Scene Zoom Level":"Niveau de Zoom de la Scène",
  "Search Element":"Rechercher un Élément",
  "Snap to Grid":"Aligner sur la Grille",
  "Snap to Guide":"Aligner sur le Guide",
  "Snap to Line":"Aligner sur la Ligne",
  "Snap to Point":"Aligner sur le Point",
  "Snap to Segment":"Aligner sur le Segment",
  "texture":"texture",
  "thickness":"épaisseur",
  "Toggle Group Visibility":"Basculer la Visibilité du Groupe",
  "Un-chain all Group\'s Elements and remove Group":"Déchaîner tous les Éléments du Groupe et supprimer le Groupe",
  "Un-chain Element from Group":"Déchaîner l'Élément du Groupe",
  "Undo (CTRL-Z)": "Annuler (CTRL-Z)",
  "Redo (CTRL-Y)": "Rétablir (CTRL-Y)",
  "Undo": "Annuler",
  "Redo": "Rétablir",
  "Unselect": "Désélectionner",
  "Vertical":"Vertical",
  "width": "largeur",
  "Would you want to start a new Project?": "Voulez-vous commencer un nouveau Projet?",
  "Zoom in": "Zoomer",
  "Zoom out": "Dézoomer",
  "2D Floor Plan": "Plan 2D",
  "Loading planner...": "Chargement du planificateur...",
  "Multiple elements selected": "Plusieurs éléments sélectionnés",
  "Layer Items": "Éléments de couche",
  "Floor Information": "Informations sur le sol",
  "Selected Layer": "Couche sélectionnée",
  "Layer 1": "Couche 1",
  "View": "Vue",
  "Camera": "Caméra",
  "👁️ Auto-hide Walls": "👁️ Masquer automatiquement les murs",
  "Structure": "Structure",
  "🧱 Walls": "🧱 Murs",
  "🚪 Doors": "🚪 Portes",
  "🪟 Windows": "🪟 Fenêtres",
  "Objects": "Objets",
  "🪑 Furniture": "🪑 Meubles",
  "Helpers & Guides": "Assistants et guides",
  "📐 Floor Grid": "📐 Grille du sol",
  "➕ Axis Helpers": "➕ Aides d'axes",
  "📍 Markers": "📍 Marqueurs",
  "📏 Guides": "📏 Guides",
  "⬜ Bounding Boxes": "⬜ Boîtes englobantes",
  "X": "X",
  "Y": "Y",
  "Errors": "Erreurs",
  "Warnings": "Avertissements",
  "Millimetres (mm)": "Millimètres (mm)",
  "Centimetres (cm)": "Centimètres (cm)",
  "Metres (m)": "Mètres (m)",
  "Inches (in)": "Pouces (in)",
  "Feet (ft)": "Pieds (ft)",
  "User": "Utilisateur",
  "Free": "Gratuit",
  "Floor Plan": "Plan d'étage",
  "Gallery": "Galerie",
  "Render": "Rendu",
  "Floor Plan Tools": "Outils de plan",
  "Draw Room": "Dessiner une pièce",
  "Draw Straight Wall": "Dessiner un mur droit",
  "Draw Area": "Dessiner une zone",
  "Draw Arc Wall": "Dessiner un mur en arc",
  "Doors & Windows": "Portes et fenêtres",
  "Door Opening": "Ouverture de porte",
  "Window Opening": "Ouverture de fenêtre",
  "Beam": "Poutre",
  "Column": "Colonne",
  "Measure Tool": "Outil de mesure",
  "Measure distances and areas": "Mesurer les distances et les surfaces",
  "Align Objects": "Aligner les objets",
  "Align multiple objects": "Aligner plusieurs objets",
  "Distribute": "Distribuer",
  "Distribute objects evenly": "Distribuer uniformément les objets",
  "Group Objects": "Grouper les objets",
  "Group multiple objects": "Grouper plusieurs objets",
  "Duplicate": "Dupliquer",
  "Duplicate selected objects": "Dupliquer les objets sélectionnés",
  "Mirror": "Miroir",
  "Mirror objects horizontally": "Miroiter les objets horizontalement",
  "Rotate": "Pivoter",
  "Rotate objects precisely": "Pivoter les objets avec précision",
  "Scale": "Mettre à l'échelle",
  "Scale objects proportionally": "Mettre à l'échelle proportionnellement",
  "Design Gallery": "Galerie de designs",
  "by": "par",
  "votes": "votes",
  "Snap": "Accrochage",
  "Point": "Point",
  "Line": "Ligne",
  "Segment": "Segment",
  "Grid": "Grille",
  "Guide": "Guide",
  "Reset zoom": "Réinitialiser le zoom",
  "Add layer": "Ajouter une couche",
  "Hide": "Masquer",
  "Show": "Afficher",
  "Rename": "Renommer"
};
