export default {
  "+ Add Horizontal Giude":"+ Aggiungi Guida Orizzontale",
  "+ Add Vertical Giude":"+ Aggiungi Guida Verticale",
  "2D View": "Vista 2D",
  "3D First Person": "3D Prima persona",
  "3D View": "Vista 3D",
  "All": "Tutto",
  "Altitude": "Quota",
  "altitude": "Quota",
  "Annotation": "Annotazione",
  "Areas":"Aree",
  "Change Language": "Cambia lingua",
  "Cancel": "Annulla",
  "Catalog" : "Catalogo",
  "Chain selected Elements to Group":"Collega l'Elemento selzionato al Gruppo",
  "Circular":"Circolare",
  "Clear": "Cancella",
  "color":"colore",
  "Configure layer": "Configura livello",
  "Configure project": "Configura progetto",
  "Confirm": "Conferma",
  "Copy":"Copia",
  "Custom furniture": "Mobili personalizzati",
  "Decoration": "Decorazione",
  "Delete group and all Elements":"Elimina Gruppo e tutti i suoi Elementi",
  "Delete layer": "Elimina livello",
  "Delete": "Elimina",
  "Dimension": "Dimensione",
  "Elements on layer {0}": "Elementi nel livello {0}",
  "Elements":"Elementi",
  "Finishes": "Finiture",
  "Floor Thickness": "Spessore del pavimento",
  "Furniture": "Mobili",
  "Get Screenshot" : "Cattura uno screenshot",
  "Group [{0}]":"Gruppo [{0}]",
  "Group's Barycenter":"Baricentro del Gruppo",
  "Group's Elements":"Elementi del Gruppo",
  "Groups":"Gruppi",
  "Guides":"Guide",
  "height": "Altezza",
  "Help": "Aiuto",
  "Holes":"Buchi",
  "Horizontal":"Orizzontale",
  "Items":"Oggetti",
  "Last Selected":"Ultimi Selezionati",
  "Layer config": "Configurazione livello",
  "Layer":"Livello",
  "Layers": "Livelli",
  "Length":"Lunghezza",
  "Lines":"Linee",
  "Load Project": "Carica Progetto",
  "Load project": "Carica progetto",
  "Mouse X Coordinate":"Coordinata X del Mouse",
  "Mouse Y Coordinate":"Coordinata Y del Mouse",
  "Name" : "Nome",
  "New Empty Group":"Crea Gruppo Vuoto",
  "New Group from selected":"Crea Gruppo dai selezionati",
  "New layer": "Nuovo livello",
  "New project": "Nuovo progetto",
  "opacity": "Opacità",
  "Open catalog": "Apri catalogo",
  "order":"Ordine",
  "Pan": "Muovi",
  "Parametric ceiling": "Soffitto parametrico",
  "Paste":"Incolla",
  "Project config": "Configurazione progetto",
  "Properties": "Proprietà",
  "Properties: [{0}] {1}": "Proprietà: [{0}] {1}",
  "Prototype":"Prototipo",
  "Reference line": "Linea di riferimento",
  "Reset": "Annulla",
  "Room Height": "Altezza della stanza",
  "Rotation" : "Rotazione",
  "Save project": "Salva progetto",
  "Save" : "Salva",
  "Scene Zoom Level":"Livello di Zoom della Scena",
  "Search Element":"Cerca Elemento",
  "Snap to Grid":"Snap alla Griglia",
  "Snap to Guide":"Snap alla Guida",
  "Snap to Line":"Snap alla Linea",
  "Snap to Point":"Snap al Punto",
  "Snap to Segment":"Snap al Segmento",
  "texture":"texture",
  "thickness":"spessore",
  "Toggle Group Visibility":"Varia la visibilità del Gruppo",
  "Un-chain all Group\'s Elements and remove Group":"Elimina il Gruppo e scollega tutti gli Elementi appartenenti",
  "Un-chain Element from Group":"Scollega l'Elemento dal Gruppo",
  "Undo (CTRL-Z)": "Annulla (CTRL-Z)",
  "Redo (CTRL-Y)": "Ripeti (CTRL-Y)",
  "Undo": "Annulla",
  "Redo": "Ripeti",
  "Unselect": "Deseleziona",
  "Vertical":"Verticale",
  "width": "Larghezza",
  "Would you want to start a new Project?": "Vuoi iniziare un nuovo progetto?",
  "Zoom in": "Ingrandisci",
  "Zoom out": "Riduci",
  "2D Floor Plan": "Pianta 2D",
  "Loading planner...": "Caricamento planner...",
  "Multiple elements selected": "Elementi multipli selezionati",
  "Layer Items": "Elementi del livello",
  "Floor Information": "Informazioni pavimento",
  "Selected Layer": "Livello selezionato",
  "Layer 1": "Livello 1",
  "View": "Vista",
  "Camera": "Fotocamera",
  "👁️ Auto-hide Walls": "👁️ Nascondi automaticamente i muri",
  "Structure": "Struttura",
  "🧱 Walls": "🧱 Muri",
  "🚪 Doors": "🚪 Porte",
  "🪟 Windows": "🪟 Finestre",
  "Objects": "Oggetti",
  "🪑 Furniture": "🪑 Arredi",
  "Helpers & Guides": "Aiuti e guide",
  "📐 Floor Grid": "📐 Griglia pavimento",
  "➕ Axis Helpers": "➕ Assistenti assi",
  "📍 Markers": "📍 Marcatori",
  "📏 Guides": "📏 Guide",
  "⬜ Bounding Boxes": "⬜ Bounding box",
  "X": "X",
  "Y": "Y",
  "Errors": "Errori",
  "Warnings": "Avvisi",
  "Millimetres (mm)": "Millimetri (mm)",
  "Centimetres (cm)": "Centimetri (cm)",
  "Metres (m)": "Metri (m)",
  "Inches (in)": "Pollici (in)",
  "Feet (ft)": "Piedi (ft)",
  "User": "Utente",
  "Free": "Gratis",
  "Floor Plan": "Pianta",
  "Gallery": "Galleria",
  "Render": "Render",
  "Floor Plan Tools": "Strumenti pianta",
  "Draw Room": "Disegna stanza",
  "Draw Straight Wall": "Disegna muro dritto",
  "Draw Area": "Disegna area",
  "Draw Arc Wall": "Disegna muro ad arco",
  "Doors & Windows": "Porte e finestre",
  "Door Opening": "Apertura porta",
  "Window Opening": "Apertura finestra",
  "Beam": "Trave",
  "Column": "Colonna",
  "Measure Tool": "Strumento misura",
  "Measure distances and areas": "Misura distanze e aree",
  "Align Objects": "Allinea oggetti",
  "Align multiple objects": "Allinea più oggetti",
  "Distribute": "Distribuisci",
  "Distribute objects evenly": "Distribuisci gli oggetti uniformemente",
  "Group Objects": "Raggruppa oggetti",
  "Group multiple objects": "Raggruppa più oggetti",
  "Duplicate": "Duplica",
  "Duplicate selected objects": "Duplica oggetti selezionati",
  "Mirror": "Specchia",
  "Mirror objects horizontally": "Specchia orizzontalmente gli oggetti",
  "Rotate": "Ruota",
  "Rotate objects precisely": "Ruota oggetti con precisione",
  "Scale": "Scala",
  "Scale objects proportionally": "Scala gli oggetti proporzionalmente",
  "Design Gallery": "Galleria design",
  "by": "di",
  "votes": "voti",
  "Snap": "Snap",
  "Point": "Punto",
  "Line": "Linea",
  "Segment": "Segmento",
  "Grid": "Griglia",
  "Guide": "Guida",
  "Reset zoom": "Reimposta zoom",
  "Add layer": "Aggiungi livello",
  "Hide": "Nascondi",
  "Show": "Mostra",
  "Rename": "Rinomina"
};
