export default {
  "+ Add Horizontal Giude":"+ Добавить горизонтальное руководство",
  "+ Add Vertical Giude":"+ Добавить вертикальное руководство",
  "2D View": "Плоский вид",
  "3D First Person": "3D от первого лица",
  "3D View": "Объёмный вид",
  "All": "Все",
  "altitude": "высота",
  "Altitude": "Высота",
  "Annotation": "Аннотация",
  "Areas": "Поверхности",
  "Change Language": "Изменить язык",
  "Cancel": "Отмена",
  "Catalog": "Каталог",
  "Chain selected Elements to Group":"Цепочка выбранных элементов в группу",
  "Circular":"круговой",
  "Clear": "Очистить",
  "color":"цвет",
  "Configure layer": "Настроить слой",
  "Configure project": "Настроить проект",
  "Confirm": "подтвердить",
  "Copy": "Копировать",
  "Custom furniture": "Пользовательская мебель",
  "Decoration": "Декор",
  "Delete group and all Elements":"Удалить группу и все элементы",
  "Delete layer": "Удалить слой",
  "Delete": "Удалить",
  "Dimension": "Размер",
  "Elements on layer {0}": "Элементов на слое {0}",
  "Elements":"элементы",
  "Finishes": "Отделка",
  "Floor Thickness": "Толщина пола",
  "Furniture": "Мебель",
  "Get Screenshot": "Сделать снимок экрана",
  "Group [{0}]":"группа [{0}]",
  "Group's Barycenter":"Барицентр группы",
  "Group's Elements":"Элементы группы",
  "Groups":"группы",
  "Guides":"руководства",
  "height": "высота",
  "Help": "Помощь",
  "Holes": "Проёмы",
  "Horizontal":"горизонтальный",
  "Items": "Предметы",
  "Last Selected": "Последний выбраный",
  "Layer config": "Настройка слоя",
  "Layer":"Слой",
  "Layers": "Слои",
  "Length": "Длинна",
  "Lines": "Линии",
  "Load Project": "Загрузить проект",
  "Load project": "Загрузить проект",
  "Mouse X Coordinate": "X-координата курсора",
  "Mouse Y Coordinate": "Y-координата курсора",
  "Name": "Название",
  "New Empty Group":"Новая пустая группа",
  "New Group from selected":"Новая группа из выбранных",
  "New layer": "Новый слой",
  "New project": "Новый проект",
  "opacity": "непрозрачность",
  "Open catalog": "Открыть каталог",
  "order": "порядок",
  "Pan": "Двигать",
  "Parametric ceiling": "Параметрический потолок",
  "Paste": "Вставить",
  "Project config": "Настройка проекта",
  "Properties": "Свойства",
  "Properties: [{0}] {1}": "Свойства: [{0}] {1}",
  "Prototype":"Опытный образец",
  "Reference line": "Линия ссылки",
  "Reset": "Сброс",
  "Room Height": "Высота комнаты",
  "Rotation": "Вращение",
  "Save project": "Сохранить проект",
  "Save": "Сохранить",
  "Scene Zoom Level": "Уровень приближениия сцены",
  "Search Element": "Поиск",
  "Snap to Grid": "Привязка к сетке",
  "Snap to Guide": "Привязать к руководству",
  "Snap to Line": "Привязка к линии",
  "Snap to Point": "Привязка к точке",
  "Snap to Segment": "Привязка к сегменту",
  "texture":"текстура",
  "thickness":"толщина",
  "Toggle Group Visibility":"Переключить видимость группы",
  "Un-chain all Group\'s Elements and remove Group":"Удалить цепочку элементов группы и удалить группу",
  "Un-chain Element from Group":"Unchain Element из группы",
  "Undo (CTRL-Z)": "Отменить действие (CTRL-Z)",
  "Redo (CTRL-Y)": "Повторить (CTRL-Y)",
  "Undo": "Отменить",
  "Redo": "Повторить",
  "Unselect": "Снять выделене",
  "Vertical":"вертикальный",
  "width": "ширина",
  "Would you want to start a new Project?": "Начать новый проект?",
  "Zoom in": "Приблизить",
  "Zoom out": "Отдалить",
  "2D Floor Plan": "План 2D",
  "Loading planner...": "Загрузка планировщика...",
  "Multiple elements selected": "Выбрано несколько элементов",
  "Layer Items": "Элементы слоя",
  "Floor Information": "Информация о полу",
  "Selected Layer": "Выбранный слой",
  "Layer 1": "Слой 1",
  "View": "Вид",
  "Camera": "Камера",
  "👁️ Auto-hide Walls": "👁️ Автоскрытие стен",
  "Structure": "Структура",
  "🧱 Walls": "🧱 Стены",
  "🚪 Doors": "🚪 Двери",
  "🪟 Windows": "🪟 Окна",
  "Objects": "Объекты",
  "🪑 Furniture": "🪑 Мебель",
  "Helpers & Guides": "Помощники и направляющие",
  "📐 Floor Grid": "📐 Сетка пола",
  "➕ Axis Helpers": "➕ Помощники осей",
  "📍 Markers": "📍 Маркеры",
  "📏 Guides": "📏 Направляющие",
  "⬜ Bounding Boxes": "⬜ Ограничивающие рамки",
  "X": "X",
  "Y": "Y",
  "Errors": "Ошибки",
  "Warnings": "Предупреждения",
  "Millimetres (mm)": "Миллиметры (mm)",
  "Centimetres (cm)": "Сантиметры (cm)",
  "Metres (m)": "Метры (m)",
  "Inches (in)": "Дюймы (in)",
  "Feet (ft)": "Футы (ft)",
  "User": "Пользователь",
  "Free": "Бесплатно",
  "Floor Plan": "План",
  "Gallery": "Галерея",
  "Render": "Рендер",
  "Floor Plan Tools": "Инструменты плана",
  "Draw Room": "Нарисовать комнату",
  "Draw Straight Wall": "Нарисовать прямую стену",
  "Draw Area": "Нарисовать область",
  "Draw Arc Wall": "Нарисовать дугообразную стену",
  "Doors & Windows": "Двери и окна",
  "Door Opening": "Дверной проем",
  "Window Opening": "Оконный проем",
  "Beam": "Балка",
  "Column": "Колонна",
  "Measure Tool": "Инструмент измерения",
  "Measure distances and areas": "Измерение расстояний и площадей",
  "Align Objects": "Выровнять объекты",
  "Align multiple objects": "Выровнять несколько объектов",
  "Distribute": "Распределить",
  "Distribute objects evenly": "Равномерно распределить объекты",
  "Group Objects": "Сгруппировать объекты",
  "Group multiple objects": "Сгруппировать несколько объектов",
  "Duplicate": "Дублировать",
  "Duplicate selected objects": "Дублировать выбранные объекты",
  "Mirror": "Отразить",
  "Mirror objects horizontally": "Отразить объекты по горизонтали",
  "Rotate": "Повернуть",
  "Rotate objects precisely": "Точно повернуть объекты",
  "Scale": "Масштаб",
  "Scale objects proportionally": "Масштабировать объекты пропорционально",
  "Design Gallery": "Галерея дизайнов",
  "by": "от",
  "votes": "голосов",
  "Snap": "Привязка",
  "Point": "Точка",
  "Line": "Линия",
  "Segment": "Сегмент",
  "Grid": "Сетка",
  "Guide": "Направляющая",
  "Reset zoom": "Сбросить масштаб",
  "Add layer": "Добавить слой",
  "Hide": "Скрыть",
  "Show": "Показать",
  "Rename": "Переименовать"
};
